### PR TITLE
Group imports by Std External Crate 

### PR DESCRIPTION
**Pull request by rlukata**
Use [group_imports = "StdExternalCrate"](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#StdExternalCrate%5C%3A) to format and group imports by:

[std, core, malloc, etc]

[extern]

[crate, super]

### CODE REVIEW

**Comment by flaub** [comment]
Nice!

For some reason we have two different `rustfmt.toml` files. We could try to consolidate later, but could you also update the one in the root of the repository? I think this one is used by cargo and maybe tools like vscode.

**Comment by rlukata** [comment]
Looks like the root `rustfmt.toml` is a symbolic link to the file `bazel/rules/rust/rustfmt.toml`.

I did a `find` on the repo and couldn't find additional files:
```
rlukata@Ramis-MBP risc0 % find . -iname "rustfmt.toml"
./rustfmt.toml
./bazel/rules/rust/rustfmt.toml

**Comment by shkoo** [comment]
Yes, I think you have to also format the stuff in methods/inner since it's a different workspace.

**Comment by rlukata** [comment]
@shkoo Looks like they're already formatted and getting formatted. I've manually tried modifying some files in `methods/inner` and they all auto-format even when I view it from the `risc0` workspace.

**Review by flaub — APPROVED** [review]

**Pull request merged**
