### PR TITLE
updating security section

### PR DESCRIPTION
**Pull request by pdg744**

### CODE REVIEW

**Comment by pdg744** [comment]
hmm neither `npx prettier . --write` nor `cargo fmt` seem to clean up the line break in the paragraph. 
is there another command i should have run?

**Comment by tzerrell** [comment]
> hmm neither `npx prettier . --write` nor `cargo fmt` seem to clean up the line break in the paragraph. is there another command i should have run?

The one breaking `C++` into
```
C+
+
```
?

**Comment by pdg744** [comment]
the rest of the doc has pretty consistent line widths, compared to the new paragraph added here

image

**Comment by tzerrell** [comment]
Oh, interesting, I didn't even notice. Maybe clippy does this? I'm just guessing

**Review by tzerrell — APPROVED** [review]
Also, approving, because overall this looks good

**Pull request merged**
