### PR TITLE
Fix bit counting in risc0_zkvm::guest::zkvm::sha::digest

### PR DESCRIPTION
**Pull request by nategraf**
As discussed in https://github.com/risc0/risc0/issues/356, the SHA-256 example started to fail it's
test during the update to risc0 v0.12. There are two causes for this.

1. There is an issue with the bit count where the message is serialized to a `buf` of u32 words, but
   the bit count is calculated as `buf.len() * 8`.
2. The semantics of of the `digest`, which in https://github.com/risc0/risc0-rust-examples/pull/45
   was originally used to replace a usage of `digest_u8_slice` method, actually returns a hash of
   the serialization of a given struct rather than directly hashing it's bytes. This is an issue in
   usage and not the `digest` method itself, so I added a comment to clarify this and hopefully
   avoid other folks making the same mistake.

Fixes: https://github.com/risc0/risc0/issues/356

### CODE REVIEW

**Comment by nategraf** [comment]
Note, I marked this as a draft until I ensure there is a test that will cover this function. Will do that today.

**Review by flaub — APPROVED** [review]
LGTM, but would like @shkoo to take a pass as well

**Review by shkoo — COMMENTED** [review]
This seems like a whole lot of copies in the guest to me.  I kind of think we should just get rid of the fn digest<T: Serialize>(...).  It doesn't seem very useful to serialize something, and then only use that serialization for generating a digest.

**Comment by nategraf** [comment]
> This seems like a whole lot of copies in the guest to me.  I kind of think we should just get rid of the fn digest<T: Serialize>(...).  It doesn't seem very useful to serialize something, and then only use that serialization for generating a digest.

Sounds good to me. It's not clear to me that this is a API folks need, and it is somewhat easy to misuse (e.g. feeding a string in to it and not getting the expected result). I'd be happy to remove it.

**Comment by flaub** [comment]
This seems fine to me as well.

**Comment by nategraf** [comment]
Removed this method in 2af13f11e365abb9381a1be3bb6e65eea96f49fd to be included in https://github.com/risc0/risc0/pull/330

**Pull request closed without merging**
