### PR TITLE
Improve executor perf

### PR DESCRIPTION
**Pull request by flaub**

### CODE REVIEW

**Review by mothran — APPROVED** [review]
Nice!!!
This nets around a ~3x perf improvement in the Executor on 16m cycle runs.

Couple follow up ticket ideas:
* Should we add a benchmark for Execute since its a critical path?
* Would it be useful to generate flamegraphs into the same repo that the benchmark / crate-validation reports go to for each PR into `main`?

**Comment by flaub** [comment]
The `fib/xxx/run` benchmark is meant to measure just execution, but I think we need to tweak it to get the numbers we'd like.

Flamegraphs generated by CI would be wonderful!

**Comment by mothran** [comment]
> The `fib/xxx/run` benchmark is meant to measure just execution, but I think we need to tweak it to get the numbers we'd like.
> 
> Flamegraphs generated by CI would be wonderful!

After the rename of `benchmarks` I will look into generating them. I was thinking of making it workflow like the benchmark-trends that is triggered on merge to main. I will go ahead and cut a ticket for it to track it outside of this PR.

**Comment by mothran** [comment]
RE CI failures: https://github.com/risc0/criterion-compare-action/pull/7

**Comment by mothran** [comment]
> ## Benchmark for Linux-cuda
> ```
>     <details open>
>       <summary>Click to hide benchmark</summary>
>       Benchmarks have changed between the two branches, unable to diff.
>     </details>
> ```
> 
> ## Benchmark for Linux-default
> ```
>     <details open>
>       <summary>Click to hide benchmark</summary>
>       Benchmarks have changed between the two branches, unable to diff.
>     </details>
> ```
> 
> ## Benchmark for macOS-default
> ```
>     <details open>
>       <summary>Click to hide benchmark</summary>
>       Benchmarks have changed between the two branches, unable to diff.
>     </details>
> ```
> 
> ## Benchmark for macOS-metal
> ```
>     <details open>
>       <summary>Click to hide benchmark</summary>
>       Benchmarks have changed between the two branches, unable to diff.
>     </details>
> ```

Well thats not exactly what I was hoping for but its close.

**Pull request merged**
