### PR TITLE
clarifying image vs imageid

### PR DESCRIPTION
**Pull request by pdg744**
Current documentation suggests verification algorithm takes the entire binary file as input. 
This PR clarifies that it just needs the ImageID

### CODE REVIEW

**Review by flaub — APPROVED** [review]

**Comment by pdg744** [comment]
@tzerrell is this way of including links fair game here?

**Review by tzerrell — APPROVED** [review]
Yes, this is fine here. If you ever want to check for yourself, you can build the docs locally with `cargo doc` from the `risc0` root directory and open the generated webpage in the browser (in `target/doc` ... e.g. on my system the relevant file is at `file:///Users/tzerrell/code/risc0/target/doc/risc0_zkvm/struct.Receipt.html`)

**Comment by mothran** [comment]
> Yes, this is fine here. If you ever want to check for yourself, you can build the docs locally with `cargo doc` from the `risc0` root directory and open the generated webpage in a browser (in `target/doc` ... e.g. on my system the relevant file is at `file:///Users/tzerrell/code/risc0/target/doc/risc0_zkvm/struct.Receipt.html`). I'm also happy to answer too though!

Additionally: `cargo doc --no-deps -p <crate-name>` to make the build way faster!

**Comment by flaub** [comment]
and there's a nice `--open` flag

**Pull request merged**
