### PR TITLE
Added clear callout to risc0-ethereum repo on ethereum examples page

### PR DESCRIPTION
**Pull request by sashaaldrick**
Based on feedback from devs at hackathons, and after a discussion with Victor, we are missing a clear CTA for the `risc0-ethereum` repo. 

Whilst I'm working on cleaning up the examples (and this `eth-examples` page alongside it), I want to add a temporary callout that "fixes" this issue for now.

## Changes 

Added a tip on 'Ethereum Examples' page seen here:

image

### CODE REVIEW

**Review by pdg744 — APPROVED** [review]
Awesome -- this is a very high impact change!

**Comment by sashaaldrick** [comment]
```$ prettier . --check && python ./link-version-check.py && remark . --quiet --frail
Checking formatting...
All matched files use Prettier code style!
website/api_versioned_docs/version-1.0/blockchain-integration/eth-examples.md:25
[blockchain-examples]: https://github.com/risc0/risc0-ethereum/tree/main/examples
github link to risc0-ethereum at ref main; expected release-1.0

website/api_versioned_docs/version-1.0/blockchain-integration/eth-examples.md:33
[steel-src]: https://github.com/risc0/risc0-ethereum/tree/main/steel
github link to risc0-ethereum at ref main; expected release-1.0

website/api_versioned_docs/version-1.0/blockchain-integration/eth-examples.md:36
[verifier-contracts]: https://github.com/risc0/risc0-ethereum/tree/main/contracts
github link to risc0-ethereum at ref main; expected release-1.0

error: script "lint" exited with code 1```

This error expects a match between the version of the docs that are being edited and the correct release branch. It also expects that you are working in the main `risc0/risc0` monorepo. 

Currently, the [main](https://github.com/risc0/risc0-ethereum) branch on `risc0-ethereum` and the [release-1.0](https://github.com/risc0/risc0-ethereum/tree/release-1.0) branch on `risc0-ethereum` have different amounts of examples in `examples/`.  

Specifically, the one the linter would accept would give only two examples, `erc20` and `erc20-counter` seen [here](https://github.com/risc0/risc0-ethereum/tree/release-1.0/examples).

@pdg744 I suggest we just force merge with the links to `risc0-ethereum` main branch and bear this in mind for the future as we will certainly link out to `risc0-ethereum` a lot more in the future.

**Comment by pdg744** [comment]
maybe we should revise the test so that links on `risc0-ethereum` are excluded... 
wdyt @sashaaldrick?

**Comment by sashaaldrick** [comment]
in the file that does the link checking, `link-version-check.py`, we already have some exceptions for `risc0-ethereum`:

EXCEPTIONS = [
    # allow refs to trusted setup ceremony assets
    "d4e427283027c28b38b8eda1562e8e0e68d1b0e2",
    # allow references to the governance example from prior versions.
    # Related issue https://github.com/risc0/risc0-ethereum/issues/1
    "bonsai/examples/governance",
    # allow link to risc0-ethereum before versioning started to match with 1.0
    "github.com/risc0/risc0-ethereum/blob/release-0.7",
    "github.com/risc0/risc0-ethereum/blob/release-0.10",
]

**Comment by sashaaldrick** [comment]
> maybe we should revise the test so that links on `risc0-ethereum` are excluded... wdyt @sashaaldrick?

I think actually the right behaviour is to link to `release-1.0` in `risc0-ethereum` and then when 1.1 is released, more examples will be available and we can update in sync then.

**Comment by pdg744** [comment]
> I think actually the right behaviour is to link to release-1.0 in risc0-ethereum and then when 1.1 is released, more examples will be available and we can update in sync then.

Perfect. IIUC, whoever is handling the release will run into this test failure & implement the update to risc0-ethereum 1.1

**Review by pdg744 — APPROVED** [review]

**Pull request merged**
