### PR TITLE
Implement CC wrapper

### PR DESCRIPTION
**Pull request by cemozerr**

### CODE REVIEW

**Comment by flaub** [comment]
@cemozerr Thanks for your contribution!

Can you provide a brief synopsis for this pull request and what problems you're solving with it?

Thanks!

**Comment by cemozerr** [comment]
Hey @flaub! This PR is for providing a wrapper to the `cc` crate that compiles to `riscv32im` with no boilerplate and reasonable defaults.

I assumed that you wouldn't waste your time with it as its currently a draft, and we probably need to clean up further. 

I'll close this for now, work on our fork and open up a PR when it's ready.

**Comment by flaub** [comment]
I think this is very useful and would love to see an end-to-end example/test of using this to build a c-based or c/rust-hybrid ELF binary that runs within R0VM.

**Comment by cemozerr** [comment]
Totally. 

We locally test end-to-end with our own fork of the [rust-secp256k1](https://github.com/Sovereign-Labs/rust-secp256k1) for example, but testing with that requires making the changes regarding the memory limit.

Maybe I can find another example that does not hit the default memory limit.

**Pull request closed without merging**
