### PR TITLE
Use crypto-bigint instead of num-bigint

### PR DESCRIPTION
**Pull request by nategraf**
As part of working on the interfaces to the bigint accelerator, I am switching usages of
num-bigint to crypto-bigint, which is better suited to the fixed-width computations we intend.

### CODE REVIEW

**Review by SchmErik — APPROVED** [review]
This looks good to me! I have a question but it's more about about the structure of the bigint circuit so I'll ask internally

**Comment by SchmErik** [comment]
@nategraf it looks like your commits are unverified

**Comment by nategraf** [comment]
> @nategraf it looks like your commits are unverified

Ah, ya I need to add my new signing key to my account. I'll do that on Monday before merging this PR.

**Comment by nategraf** [comment]
> @nategraf it looks like your commits are unverified

Ah, ya I need to add my new signing key to my account. I'll do that on Monday and before merging this PR.

**Pull request merged**
