### PR TITLE
NFC: Rename/reorg

### PR DESCRIPTION
**Pull request by flaub**
* r0vm -> zkvm
* risc0/r0vm/cpp -> risc0/zkvm/sdk/cpp
* risc0/r0vm/rust -> risc0/zkvm/sdk/rust

### CODE REVIEW

**Comment by flaub** [comment]
Feedback welcome!

**Comment by choongng** [comment]
Is the thinking here then we'd refer to it as "Risc Zero ZKVM"?

**Comment by jbruestle** [comment]
> Is the thinking here then we'd refer to it as "Risc Zero ZKVM"?

I think it's more to avoid the 'Smurf Naming Convention' where everything is prefixed with Risc Zero.  Given that the whole repo and the base dir is risc0, I think it's reasonable to just call it 'The ZKVM' and presume the r0 follows from context.  Of course if we were talking about our ZKVM vs another one (say Miden), then we would prefix.

**Review by jbruestle — APPROVED** [review]

**Review by intoverflow — APPROVED** [review]
Looking good!

In the `zkvm` path, I want to confirm that I know what each of the subdirectories are for:
* "prove" implements the runner, "verify" implements the checker
* "circuit" and "platform" are used by both "prove" and "verify
* sdk contains libs for writing host and guest apps

Is that right?

image

**Comment by choongng** [comment]
> > Is the thinking here then we'd refer to it as "Risc Zero ZKVM"?
> 
> I think it's more to avoid the 'Smurf Naming Convention' where everything is prefixed with Risc Zero. Given that the whole repo and the base dir is risc0, I think it's reasonable to just call it 'The ZKVM' and presume the r0 follows from context. Of course if we were talking about our ZKVM vs another one (say Miden), then we would prefix.

We also know from context it's ZK, could we go all the way down to "vm"? Just as clear but less awkward both in docs and code.

**Review by choongng — APPROVED** [review]
vm or zkvm, either way

**Pull request merged**
