### PR TITLE
Remove thiserror from risc0-zkp

### PR DESCRIPTION
**Pull request by flaub**
Fix for #694

### CODE REVIEW

**Comment by Brando753** [comment]
Have you considered instead of out right removing thiserror to create a std and no_std option? 

For example in code that I want to support no_std environments I would add:
```TOML
[features]
default = ["std"]
std = ["thiserror"]

[dependencies]
thiserror = { version = "1.0.40", optional = true}
```

And then I would use the std features like so:
```rust
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
extern crate alloc;

#[cfg(feature = "std")]
use thiserror::Error;

#[derive(Debug, PartialEq)]
#[cfg_attr(feature = "std", derive(Error))]
pub enum CustomError {
    /// The Prover was unable to construct a proof with your given inputs
    #[cfg_attr(
        feature = "std",
        error("The prover was unable to construct a proof with your given inputs")
    )]
    UnableToProve,
}
```

**Comment by flaub** [comment]
@Brando753 I'd like to have support for error messages in `no_std` as well. It's not much boilerplate and if it becomes onerous we could switch to `snafu`.

**Comment by Brando753** [comment]
Understood; looking over the changes, it's not that bad. If you don't have too many error structs, then it's probably not worth worrying about. I don't see the no_std crate attribute. Are you planning to add that?

**Comment by flaub** [comment]
> Understood; looking over the changes, it's not that bad. If you don't have too many error structs, then it's probably not worth worrying about. I don't see the no_std crate attribute. Are you planning to add that?

See: https://github.com/risc0/risc0/blob/main/risc0/zkp/src/lib.rs#L16

**Pull request merged**
