### PR TITLE
feat(website): zoom feature on mermaid diagrams

### PR DESCRIPTION
**Pull request by nahoc**
related: https://github.com/risc0/risc0/issues/2009

demo:
https://docs-website-git-nahoc-mermaid-zoom-risczero.vercel.app/api/next/recursion
https://docs-website-git-nahoc-mermaid-zoom-risczero.vercel.app/api/next/getting-started
https://docs-website-git-nahoc-mermaid-zoom-risczero.vercel.app/proof-system/proof-system-sequence-diagram#sequence-diagram

you need to use this now:
```react
<Mermaid
  definition={`
  flowchart TD
    %% Level 0
    getting_started["Getting Started..........
```

### CODE REVIEW

**Comment by pdg744** [comment]
LGTM, aside from the test failure

**Comment by pdg744** [comment]
i hesitate to harp on more mermaid details given how much time you've put into it recently, but i do want to flag that the themes don't look great rn in either light mode or dark mode... fine for now but seems worthwhile to either improve those or leave an open ticket for later improvement

**Comment by pdg744** [comment]
ty for digging into these details!

**Comment by nahoc** [comment]
> i hesitate to harp on more mermaid details given how much time you've put into it recently, but i do want to flag that the themes don't look great rn in either light mode or dark mode... fine for now but seems worthwhile to either improve those or leave an open ticket for later improvement

I agree they don't look great, but sadly none of the built-in themes really look good, and there's just so much customization you can do, I'd need to spend 1-2 more hours on this to get something decent (I probably will, just not the focus of that PR)

**Review by pdg744 — APPROVED** [review]
LGTM -- thank you!

**Comment by pdg744** [comment]
@nahoc bumping this -- is there anything pending here besides code owner review?

**Comment by nahoc** [comment]
closed in favor of https://github.com/risc0/risc0/pull/2523

**Pull request closed without merging**
