### PR TITLE
feat: add issue templates with fields and links to support on discord

### PR DESCRIPTION
**Pull request by nuke-web3**
This introduces some better UX in structuring input for issues and feat requests and most critically pushes support questions and issues to discrord (rather than redirect issues like #2011 ) 

:eyes:  Taken in large part from https://github.com/paritytech/polkadot-sdk/issues/new/choose that you can see what it looks like with the separated input fields and items.

It's something we can tweak over time, and improve how we ingest these - I am happy to help refine the DevRel side and help declutter the core eng side as much as possible here.

### CODE REVIEW

**Comment by pdg744** [comment]
No objections on my end, though this may be another one that's best to wait on until Frank gets back.

**Comment by nuke-web3** [comment]
as a followup I suggest we also review, clean up / migrate and then disable github discussions on all our user facing repos https://github.com/risc0/devrel/issues/106 - adding a similar PR to update templates to point to discord

**Review by flaub — APPROVED** [review]
nit: we use `.yml` suffix everywhere else, but otherwise LGTM!

**Comment by nuke-web3** [comment]
updated all instances of .yaml -> .yml (found a stray in [58ddea2](https://github.com/risc0/risc0/pull/2016/commits/58ddea25b9fa7093965e250896e37f5166430615))

**Comment by nuke-web3** [comment]
might I get an assist on CI?  CI / main-status-check (pull_request) Failing after 4s - not clear what https://github.com/risc0/risc0/blob/main/.github/workflows/main.yml#L103-L127 is failing on exactly... an auto-skipped job that is required maybe?

**Pull request merged**
