### PR TITLE
Add test for po2 = 16 recursion program

### PR DESCRIPTION
**Pull request by flaub**

### CODE REVIEW

**Comment by flaub** [comment]
This is targetted for main, so it shouldn't matter if it breaks compatiblity

**Comment by nategraf** [comment]
So does that mean this will only be released with 2.0? Additionally, it does seem like, regardless of how we manage versioning and branches, the semver checks CI job should detect breaking changes with the prover API.

**Review by nategraf — APPROVED** [review]

**Comment by nategraf** [comment]
Approving this PR as the changes themselves look good. I do think there is more discussion here on versioning, at the very least so I understand our approach, but that will happen in another context.

**Comment by flaub** [comment]
I don't think anyone is using the Prover API directly, so I think the issue around versioning could be minor. I think we can make any changes we'd like to main and determine later if we need to backport a change to the stable branch. I don't think we need this change on stable AFAIK.

**Pull request merged**
