### PR TITLE
Add BigInt syscall and accelerator in rv32im circuit

### PR DESCRIPTION
**Pull request by nategraf**
Many significant use cases for the RISC Zero zkVM require implementing finite field arithmetic in
fields of cryptographic sizes (e.g. 256 bits). A key example is verification of ECDSA signatures
over secp256k1. Currently, this is prohibitively expensive to do inside the zkVM.

In order to address this, we are adding a BigInt accelerator to the rv32im circuit. This PR contains
new compiled circuit as well as the accompanying Rust code to make the functionality accessible.

In the current implementation, only modular multiplication is supported. Each input is a 256-bit
number represented as an array of `u32` values ordered from least to most significant. Using the new
`sys_bigint` call will result in the modular multiplication `x * y == z mod N` being written to the `result` pointer.

This PR is currently marked as a draft. In order make it ready to merge, the accelerator needs to
have its constraints optimized further. Additionally the interface code included in this PR needs to
be more fleshed out.

Following this PR, this functionality can be made available to developers by providing a patched
version of common cryptographic libraries, such as RustCrypto. A top candidate is to provide a
patched version of `k256` using this new `ecall` to implement multiplication.

### CODE REVIEW

**Comment by nategraf** [comment]
Ok, so the current status of this PR is that the extern handler and syscall interface are both implemented, but have not been tested because the tests are currently failing with the following trace:
```
---- tests::bigint_accel stdout ----
thread 'tests::bigint_accel' panicked at 'called `Result::unwrap()` on an `Err` value: array::at

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/backtrace.rs:332:13
   3: anyhow::kind::Adhoc::new
             at /Users/victorgraf/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.70/src/kind.rs:70:36
   4: risc0_circuit_rv32im::cpp::call_step
             at /Users/victorgraf/risc0/risc0-bigint/risc0/circuit/rv32im/src/cpp.rs:200:13
   5: risc0_circuit_rv32im::cpp::<impl risc0_zkp::adapter::CircuitStep<risc0_core::field::baby_bear::Elem> for risc0_circuit_rv32im::CircuitImpl>::step_exec
             at /Users/victorgraf/risc0/risc0-bigint/risc0/circuit/rv32im/src/cpp.rs:75:9
   6: risc0_zkp::prove::executor::Executor<F,C,S>::step
             at /Users/victorgraf/risc0/risc0-bigint/risc0/zkp/src/prove/executor.rs:126:22
   7: risc0_zkvm::prove::exec::RV32Executor<H>::run::{{closure}}
             at ./src/prove/exec.rs:1013:48
   8: risc0_zkvm::prove::loader::LoaderImpl<F>::next_fini
             at ./src/prove/loader.rs:250:9
   9: risc0_zkvm::prove::loader::LoaderImpl<F>::body
             at ./src/prove/loader.rs:229:17
  10: risc0_zkvm::prove::loader::Loader::load
             at ./src/prove/loader.rs:373:9
  11: risc0_zkvm::prove::exec::RV32Executor<H>::run
             at ./src/prove/exec.rs:1013:22
  12: risc0_zkvm::prove::Prover::run_with_hal
             at ./src/prove/mod.rs:494:23
  13: risc0_zkvm::prove::Prover::run
             at ./src/prove/mod.rs:453:17
  14: risc0_zkvm::tests::bigint_accel::test_impl
             at ./src/tests.rs:310:19
  15: risc0_zkvm::tests::bigint_accel
             at ./src/tests.rs:288:1
  16: risc0_zkvm::tests::bigint_accel::{{closure}}
             at ./src/tests.rs:288:1
  17: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
  19: test::__rust_begin_short_backtrace
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/test/src/lib.rs:599:18
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/alloc/src/boxed.rs:1987:9
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:483:40
  23: std::panicking::try
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:447:19
  24: std::panic::catch_unwind
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panic.rs:137:14
  25: test::run_test_in_process
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/test/src/lib.rs:622:27
  26: test::run_test::run_test_inner::{{closure}}
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/test/src/lib.rs:516:39
  27: test::run_test::run_test_inner::{{closure}}
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/test/src/lib.rs:543:37
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/sys_common/backtrace.rs:121:18
  29: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/thread/mod.rs:551:17
  30: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/panic/unwind_safe.rs:271:9
  31: std::panicking::try::do_call
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:483:40
  32: std::panicking::try
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:447:19
  33: std::panic::catch_unwind
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panic.rs:137:14
  34: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/thread/mod.rs:550:30
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
  36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/alloc/src/boxed.rs:1987:9
  37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/alloc/src/boxed.rs:1987:9
  38: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/sys/unix/thread.rs:108:17
  39: __pthread_deallocate', risc0/zkvm/src/tests.rs:310:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/result.rs:1113:23
   4: risc0_zkvm::tests::bigint_accel::test_impl
             at ./src/tests.rs:310:19
   5: risc0_zkvm::tests::bigint_accel
             at ./src/tests.rs:288:1
   6: risc0_zkvm::tests::bigint_accel::{{closure}}
             at ./src/tests.rs:288:1
   7: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Unfortunately, I am going to be out for the next few weeks until April 17th, so I will not be able to work on fixing this right now. As of this comment, the PR is consistent with circuit commit 232cd224badf93a087e0cef7317d5d89380dd9ef

**Comment by nategraf** [comment]
Fixed the issue mentioned in https://github.com/risc0/risc0/pull/466#issuecomment-1480410021. The maximum number of elements that could be exchanged in an extern call was hardcoded in the codegen template to 32. I've increased this to 96 args and 64 outs for an extern call.

With this issue fixed, it is hopefully the case that remaining work is on the interfaces, documentation, and testing.

**Comment by nategraf** [comment]
In the current circuit implementation, `poly_fp.cpp` increases to 37190 lines, which is a 37% increase. I'll also look at the benchmarking results, but I am curious if this means we would not want to merge this version of the circuit and need to continue working on optimizations before adding it to main.

**Comment by nategraf** [comment]
All the benchmarks... improved? https://github.com/risc0/risc0/pull/466#issuecomment-1526252047

**Review by jbruestle — APPROVED** [review]
Yeah!

**Pull request merged**
