### PR TITLE
adding info for upcoming study club sessions

### PR DESCRIPTION
**Pull request by pdg744**

### CODE REVIEW

**Review by tzerrell — APPROVED** [review]
Looks good to me, thanks for adding in both places!

**Comment by pdg744** [comment]
hmm; I guess I need to run `prettier` for formatting... 
will check the prettier docs and see if i can figure it out

**Comment by pdg744** [comment]
I followed [these instructions](https://prettier.io/docs/en/install) and it seems to have worked.

**Comment by pdg744** [comment]
hmm... looks like there's something related to the term "status" that's not quite right yet...?

**Pull request merged**
