### PR TITLE
Change jal to call in zkVM entrypoint

### PR DESCRIPTION
**Pull request by nategraf**
As described in https://github.com/risc0/risc0/issues/1243, our use of the `jal` instruction in our entrypoint breaks when the jump distance becomes too far. This PR changes the instruction to the `call` psuedo-instruction to allow the assembler flexibility to solve this issue and implement a far jump.

Co-authored-by: @weikengchen
Resolves: https://github.com/risc0/risc0/issues/1243

### CODE REVIEW

**Comment by SchmErik** [comment]
@nategraf you'll likely need to update the image ID's for the guest methods

**Comment by weikengchen** [comment]
(That was what I meant by difficulty to update the Image IDs, which makes me reluctant to submit a PR.)

**Comment by flaub** [comment]
In general, ImageIDs change pretty easily and so this has never really been a determinant on whether we make a change.

**Review by flaub — APPROVED** [review]

**Comment by SchmErik** [comment]
> (That was what I meant by difficulty to update the Image IDs, which makes me reluctant to submit a PR.)

Hi @weikengchen, thanks for your contributions. I really appreciate your thoroughness and care that you take in describing issues and solutions! We're working on a contributor guide that would describe this but here's how to generate the image ID's for the test:

1) run docker daemon (on mac os, launch the docker desktop app)
2) run `cargo risczero build --manifest-path risc0/zkvm/methods/guest/Cargo.toml` directions are [here](https://github.com/risc0/risc0/blob/aaa1349dd57dbd13b0ae99cd126a508e642d181d/risc0/build/src/docker.rs)
3) update generated output values [here](https://github.com/risc0/risc0/blob/2c516c367ec3c905a5164eb1795d2beb69fe56dc/risc0/build/src/docker.rs#L236)

I hope this explanation makes it less painful!

**Pull request merged**
