### PR TITLE
Restore the getrandom feature in rust-runtime.a static lib

### PR DESCRIPTION
**Pull request by nategraf**
Restore the getrandom feature in `rust-runtime.a` static lib. This static library build primarily supports the `cargo risczero test` tool, which we use in our workflows to test patched cryptography crates and potentially other crates developed for the zkVM. `getrandom` is intended to be supported, but was removed with the change of default behavior in https://github.com/risc0/risc0/pull/1162.

### CODE REVIEW

**Comment by SchmErik** [comment]
@nategraf it looks like you have some other changes in addition to the getrandom feature

**Comment by nategraf** [comment]
Sorry, yes. I was working on getting `cargo risczero test` to work, which is where the null segment ref changes come in. I'll refactor/clean this up tomorrow. I do want to land all the included changes, but the description needs to reflect the contents, and possibly two PRs are in order.

**Comment by flaub** [comment]
I think we need to get some CI around this staticlib. Ideally we'd run `cargo risczero test` somewhere in CI

**Comment by SchmErik** [comment]
superseded by #1750. closing

**Pull request closed without merging**
