### PR TITLE
Return ProveInfo from prover

### PR DESCRIPTION
**Pull request by SchmErik**
This PR changes `prover.prove()` to return a new struct called `ProveInfo` that contains the receipt, number of segments, total cycles, and total user cycles. This is helpful because it allows users to access more information about the proof generation through the prover API.

### CODE REVIEW

**Comment by SchmErik** [comment]
looks like I have merge conflicts, I'm going to convert as draft and mark it as ready after I resolve them tomorrow

**Review by mothran — COMMENTED** [review]
YAY! Just wanted to say this looks like exactly what I have needed in the past, thanks!

**Review by flaub — APPROVED** [review]
The CHANGELOG needs to be updated with this breaking change, but otherwise looks good!

**Comment by SchmErik** [comment]
> The CHANGELOG needs to be updated with this breaking change, but otherwise looks good!

Thanks for the heads up, I really appreciate it! I'll merge after updating the change log this afternoon

**Pull request merged**
