### PR TITLE
Update Solidity version in Bonsai contracts to 0.8.20

### PR DESCRIPTION
**Pull request by nategraf**
A third party review of our smart contracts recommended an updated Solidity version. This PR updates the Solidity version on all smart contracts in this repository to 0.8.20.

0.8.20 was picked because it is the version currenrly used by the [OpenZeppelin contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) as of their most recent release, 5.0.1.

### CODE REVIEW

**Comment by nategraf** [comment]
Converting this to a draft since I realized I should update the submodules along with this version update.

**Comment by SchmErik** [comment]
@nategraf is this still needed? If not, could we close it?

**Comment by nategraf** [comment]
I actually have not taken care of this yet, so I need to do that

**Comment by nategraf** [comment]
Relevant code will be removed from this repository

**Pull request closed without merging**
